[package]
name = "network-scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1" }
iced_core = "0.13.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = "1.40.0"
trust-dns-resolver = "0.23.2"
